spring:
  security: # isso aqui faz parte do security, só usar para testes rápidos ou até vai usar em profiles diferentes, mas nunca mandar isso pro git
    user:
      name: user
      password: devdojo
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_ROOT_USER:root} # Procura por ENV_ROOT_USER e usa, se não achar usa 'root'
    password: ${ENV_ROOT_PASSWORD:devdojo} # Mesma coisa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
threads:
  virtual:
    enabled: true

logging: # os dois comentados são da aula 96 - logging query parameters
  level:
    academy.devdojo: debug
#   org.hibernate.orm.jdbc.bind: trace
#   net.ttddyy.dsproxy.listener: debug
    org.springframework.security: debug

server:
  port: 8090
  servlet:
    context-path: /

  error:
    include-stacktrace: on_param
    include-binding-errors: always
    include-message: always
  tomcat:
    threads:
      max: 20

management: # habilitando todos os endpoints do actuator
  server: # geralmente o actuator roda em uma porta diferente
    port: 8989
  endpoints:
    web:
      exposure:
        include: "*"

brasil-api: # aprendendo a usar RestClient
  base-url: ${BRASIL_API_BASE_URL:https://brasilapi.com.br/api}
  cep-uri: ${BRASIL_API_URI:/cep/v1/{cep}}

# Essas variáveis de ambiente estão no arquivo .env do mesmo diretório

# Para usar as variáveis no código java exemplo:
# @Value("{brasil-api.base-url}")
# private String url;
# porém, o devdojo aconselha usar @ConfigurationProperties invés disso.